FROM python:3.10-slim

RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker

WORKDIR /opt/dagster/app
COPY ./app /opt/dagster/app

EXPOSE 4000

CMD ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-f", "definitions.py"]